name: AutoPkg

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  TAG_NAME: "自动打包"


jobs:
  build-ldr-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: make all

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        prerelease: true
        draft: false
        files: |
          disk/*
